import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/scrollsmoother";
import { TooltipProvider } from "@/components/ui/tooltip";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={
        cn(
          "h-full", 
          "antialiased", 
          "font-sans", 
      )}
    >
      <body className="min-h-full w-full flex flex-col font-Louis">
        <SmoothScrollProvider>
          <TooltipProvider>
 
            {children}

            <Footer />
 
          </TooltipProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
