import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/scrollsmoother";
import { TooltipProvider } from "@/components/ui/tooltip";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Plus_Jakarta_Sans, Mulish } from 'next/font/google'

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-jakarta',
})

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-mulish',
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();
  
  return (
    <html
      lang="en"
      className={
        cn(
          "h-full",
          "antialiased",
          `${jakarta.variable} ${mulish.variable}`
        )}
    >
      <link
        rel="preload"
        href="/fonts/Louis.ttf"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
      />

      <link
        rel="preload"
        href="/fonts/Relicta-Light.otf"
        as="font"
        type="font/woff2"
        crossOrigin="anonymous"
      />

      <body className="min-h-full w-full flex flex-col ">
        <NextIntlClientProvider messages={ messages }>
          <SmoothScrollProvider>
            <TooltipProvider>

              {children}

            </TooltipProvider>
          </SmoothScrollProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
