import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/scrollsmoother";
import { TooltipProvider } from "@/components/ui/tooltip";

import "@/i18n";
import { useTranslation } from "react-i18next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { Plus_Jakarta_Sans, Mulish } from 'next/font/google'
import I18nProvider from "@/lib/i18n-provider";

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-jakarta',
})

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-mulish',
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={
        cn(
          "h-full",
          "antialiased",
          `${jakarta.variable} ${mulish.variable}`
        )}
    >
      <link
        rel="preload"
        href="/fonts/Louis.ttf"
        as="font"
        type="font/ttf"
        crossOrigin="anonymous"
      />

      <link
        rel="preload"
        href="/fonts/Relicta-Light.otf"
        as="font"
        type="font/otf"
        crossOrigin="anonymous"
      />

      <body className="min-h-full w-full flex flex-col ">
          <SmoothScrollProvider>
            <I18nProvider>
            <TooltipProvider>

              {children}

            </TooltipProvider>
            </I18nProvider>
          </SmoothScrollProvider>
      </body>
    </html>
  );
}
