import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/scrollsmoother";
import { TooltipProvider } from "@/components/ui/tooltip";
import { NextIntlClientProvider } from "next-intl";

import { Playfair_Display, Manrope } from 'next/font/google'
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-playfair", 
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-manrope",
});


export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}


export default async function RootLayout({
  children,
  params 
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {

  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={
        cn(
          "h-full",
          "antialiased",
          `${playfair.variable} ${manrope.variable}`
        )}
    >

      <body className="min-h-full w-full flex flex-col">
          <SmoothScrollProvider>
            <NextIntlClientProvider messages={messages}>
              <TooltipProvider>

                {children}

              </TooltipProvider>
            </NextIntlClientProvider>
          </SmoothScrollProvider>
      </body>
    </html>
  );
}
